// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVOFMEpmP9WQOvGajhOT3eETSadzZk3x8',
    appId: '1:209003375731:web:803357b3b61cb967a7ce06',
    messagingSenderId: '209003375731',
    projectId: 'flutterlogin-98191',
    authDomain: 'flutterlogin-98191.firebaseapp.com',
    storageBucket: 'flutterlogin-98191.firebasestorage.app',
    measurementId: 'G-T408PF24E1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6dEw7jukOuUVBkjic-0-xlp9IHYEvHt0',
    appId: '1:209003375731:android:15ae833ecba2c2b5a7ce06',
    messagingSenderId: '209003375731',
    projectId: 'flutterlogin-98191',
    storageBucket: 'flutterlogin-98191.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk_7TpsCgbm9Ma6I1Dg15joxM4E6PkurM',
    appId: '1:209003375731:ios:a026e66b794cd3d3a7ce06',
    messagingSenderId: '209003375731',
    projectId: 'flutterlogin-98191',
    storageBucket: 'flutterlogin-98191.firebasestorage.app',
    iosBundleId: 'com.example.flutterUnicode1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk_7TpsCgbm9Ma6I1Dg15joxM4E6PkurM',
    appId: '1:209003375731:ios:a026e66b794cd3d3a7ce06',
    messagingSenderId: '209003375731',
    projectId: 'flutterlogin-98191',
    storageBucket: 'flutterlogin-98191.firebasestorage.app',
    iosBundleId: 'com.example.flutterUnicode1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVOFMEpmP9WQOvGajhOT3eETSadzZk3x8',
    appId: '1:209003375731:web:fdb1bddd0d046070a7ce06',
    messagingSenderId: '209003375731',
    projectId: 'flutterlogin-98191',
    authDomain: 'flutterlogin-98191.firebaseapp.com',
    storageBucket: 'flutterlogin-98191.firebasestorage.app',
    measurementId: 'G-G8RM6W9P95',
  );
}
